project_id = "ukycdbvasmeuralmvvcm"

[functions.create-checkout]
verify_jwt = false

[functions.admin-update-product]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.sync-subscription]
verify_jwt = false

[functions.admin-list-users]
verify_jwt = false

[functions.test-webhook-secret]
verify_jwt = false

[functions.compare-model]
verify_jwt = false
[functions.decode-conversation]
verify_jwt = false

[functions.analyze-group]
verify_jwt = false

[functions.group-share]
verify_jwt = false


[functions.roast-us]
verify_jwt = false

[functions.roast-share]
verify_jwt = false

[functions.analysis-share]
verify_jwt = false

[functions.analyze-group-roast]
verify_jwt = false

[functions.group-roast-data]
verify_jwt = false
