import type { AnalysisResult, ContextData } from "@/lib/analysis-types";
import type { GroupResultJson, GroupStatsJson } from "@/lib/group/types";
import type { GroupRoastResult } from "@/lib/groupRoast/types";
import type { RoastResultJson } from "@/lib/roast/types";
import type { WrappedStats } from "@/lib/wrapped/stats";

export const deepContext: ContextData = { name1: "Maya", name2: "Jonas", relationship_stage: "dating", duration: "8 months", goal: "Understand our planning loop" };
export const deepResult: AnalysisResult = {
 coverage:{messages_supplied:248,messages_analyzed:248,messages_read_by_ai:248,messages_quoted_verbatim:5,chunk_count:1,failed_chunks:0,full_history_read:true},
 meta:{messages_analyzed:248,analysis_confidence:"medium",safety_concern:false},
 headline:{score:76,tier_label:"Strong connection, uneven clarity",vibe_summary:"Warmth is easy here; logistics become harder when reassurance stays implied."},
 sub_scores:{communication:72,emotional_safety:82,spark:79},
 communication_diagnostic:{response_time_asymmetry:"Jonas is slower during work hours",initiator_balance:"Maya 56% · Jonas 44%",message_length_asymmetry:"Maya writes about 1.3× more",question_ratio:"Maya asks 58% of questions",key_observation:"Both repair quickly, but plans drift when neither states the reassurance they need."},
 attachment_profiles:{Maya:{primary_style:"anxious",scores:{secure:61,anxious:72,avoidant:18,disorganized:8},confidence:"medium",evidence_quotes:["Are we still on for Friday? No stress if work is wild."]},Jonas:{primary_style:"secure",scores:{secure:74,anxious:20,avoidant:35,disorganized:6},confidence:"medium",evidence_quotes:["Yes. Sorry—I should have answered the actual question."]}},
 four_horsemen:{criticism:{present:false},contempt:{present:false},defensiveness:{present:true,evidence_quote:"I said work was bad, I wasn't ignoring you."},stonewalling:{present:false}},
 bids_for_connection:{turned_toward_pct:78,turned_away_pct:18,turned_against_pct:4},
 love_languages:{Maya:["quality time","words of affirmation"],Jonas:["acts of service","quality time"]},
 green_flags:[{title:"Repair attempts land",evidence:"Both acknowledge misunderstandings and return to the question."},{title:"Mutual curiosity",evidence:"Both ask follow-up questions about each other's day."}],
 yellow_flags:[{title:"Reassurance gets hidden inside logistics",evidence:"Planning questions carry emotional weight that neither names directly."}],red_flags:[],
 hidden_pattern:{title:"The logistics–reassurance loop",description:"Maya asks about the plan to check connection; Jonas answers the practical detail and misses the emotional question. A direct reassurance plus a concrete update breaks the loop."},
 conversation_prompts:["When plans are uncertain, what kind of update helps each of us feel considered?","Can we distinguish 'I need reassurance' from 'I need a schedule'?","What repair phrase feels natural when one of us misses the real question?"],
 compatibility_implication:"Their strongest shared pattern is quick repair. The growth edge is making reassurance explicit before solving logistics."
};
export const quickExample = { verdict:"Interested, but trying not to overpromise", read:"The message is warm and specific, but the softener suggests they are protecting against disappointing you if work runs late.", signals:["They propose a real day rather than saying 'sometime'.","The apology comes before the boundary, which softens it.","They leave the time open, so a concrete follow-up is still needed."], flag:"No clear red flag in this message alone. Context could change the read.", replies:[{tone:"Warm",text:"Thursday works. Want to pick a time once you know how work looks?"},{tone:"Direct",text:"I'm free Thursday after 7—does that work for you?"},{tone:"Low-key",text:"Thursday could work. Let me know when you know your timing."}] };
export const groupResult: GroupResultJson = {group_title:"The Calendar Coalition",group_summary:"Four friends keep plans alive through practical follow-through, quick humor, and one recurring gap: decisions stay open until Maya turns options into a question.",participants:[{id:"p1",display_name:"Maya"},{id:"p2",display_name:"Dev"},{id:"p3",display_name:"Priya"},{id:"p4",display_name:"Sam"}],role_cards:[{participant_id:"p1",role:"The Closer",headline:"Turns a cloud of ideas into an actual plan.",why:"Maya asks most decision questions and summarizes agreed details.",evidence:"So Saturday at 7, mine?"},{participant_id:"p2",role:"The Fixer",headline:"Answers practical requests before the thread can wander.",why:"Dev volunteers for errands and confirms tasks clearly.",evidence:"I'll sort snacks."},{participant_id:"p3",role:"The Spark",headline:"Starts ideas and keeps everyone responding.",why:"Priya initiates the most social plans and follows up warmly.",evidence:"Should we do food or just snacks?"},{participant_id:"p4",role:"The Cameo",headline:"Fewer messages, reliably timed.",why:"Sam contributes less often, so this role is lower-confidence; the available messages mostly confirm attendance.",evidence:"Can't, work thing."}],balance:{note:"Maya and Priya contribute 59% of messages; Dev supplies practical follow-through. Sam has sparse data, so conclusions about Sam are limited.",flag:"moderately uneven"},initiation:{available:true,note:"Priya starts 4 of 9 dated conversation sessions; Maya starts 3."},unanswered:{note:"Most direct questions receive an answer. Timing questions are the likeliest to need a second prompt."},repair:{note:"Small misses are repaired with acknowledgment and a concrete next step rather than blame."},group_strengths:["People volunteer help without scorekeeping.","Humor supports decisions rather than derailing them.","The group welcomes a clear summary."],subgroups:[{note:"Maya and Priya often build the plan together; Dev then operationalizes it.",confidence:"medium"}],suggestions:["End planning threads with one owner, time and location.","Ask quieter members a direct low-pressure preference question."],alternatives:["The uneven message share may reflect availability during this period, not influence outside the chat."],confidence:"medium",coverage:{messages_supplied:312,messages_analyzed:312,messages_read_by_ai:312,messages_quoted_verbatim:4,chunk_count:1,failed_chunks:0,full_history_read:true,sampled:false,date_start:"2026-05-01",date_end:"2026-06-30",timestamp_coverage_pct:100}};
export const groupStats: GroupStatsJson = {message_count:312,participant_count:4,has_timestamps:true,timestamp_coverage_pct:100,total_questions:47,total_unanswered_questions:6,participants:[{id:"p1",messages:96,share_pct:31,avg_words:8,questions_asked:18,questions_unanswered:2,emoji_count:12,apology_tokens:2,initiations:3,median_response_minutes:11,quiet:false},{id:"p2",messages:75,share_pct:24,avg_words:6,questions_asked:7,questions_unanswered:1,emoji_count:6,apology_tokens:1,initiations:1,median_response_minutes:8,quiet:false},{id:"p3",messages:89,share_pct:28,avg_words:9,questions_asked:17,questions_unanswered:2,emoji_count:18,apology_tokens:1,initiations:4,median_response_minutes:6,quiet:false},{id:"p4",messages:52,share_pct:17,avg_words:5,questions_asked:5,questions_unanswered:1,emoji_count:4,apology_tokens:0,initiations:1,median_response_minutes:38,quiet:true}]};
export const groupRoastResult: GroupRoastResult={group_headline:"Four planners enter. One plan eventually leaves.",group_personality:"A high-functioning committee disguised as a snack discussion: warm, responsive, and constitutionally unable to choose a time on the first attempt.",participants:groupResult.participants,participant_roles:[{participant_id:"p1",role:"Chief Calendar Officer",headline:"Has never met an open loop she couldn't turn into a poll.",observed_behavior:"Maya asks decision questions and restates settled details.",evidence:"So Saturday at 7, mine?",confidence:"high"},{participant_id:"p2",role:"Minister of Snacks",headline:"Quiet until logistics need rescuing, then suddenly has a spreadsheet.",observed_behavior:"Dev volunteers for practical tasks and confirms completion.",evidence:"I'll sort snacks.",confidence:"high"},{participant_id:"p3",role:"Director of New Business",headline:"Launches three plans before breakfast and somehow gets replies to all of them.",observed_behavior:"Priya starts the most social planning threads.",evidence:"Should we do food or just snacks?",confidence:"high"},{participant_id:"p4",role:"Special Guest Star",headline:"Limited screen time; excellent timing.",observed_behavior:"Sam has fewer messages in this period, mostly concise availability updates, so broader claims would be guesswork.",evidence:"Can't, work thing.",confidence:"low"}],interaction_dynamics:["Priya generates options; Maya turns them into decisions.","Dev's practical replies keep plans moving.","Sam's lower volume means the chat shows availability, not a full personality picture."],standout_moments:[{moment:"A snack question became a complete hosting plan in eleven messages.",evidence:"I'll sort snacks."},{moment:"The final confirmation arrived only after Maya restated the whole plan.",evidence:"So Saturday at 7, mine?"}],seriously:"This group already repairs confusion kindly. One named decision-owner per plan would reduce follow-ups without changing the warmth.",coverage:{messages_supplied:312,messages_read_by_ai:312,chunk_count:1,failed_chunks:0,full_history_read:true,date_start:"2026-05-01",date_end:"2026-06-30"}};
export const roastExample: RoastResultJson={headline:"Maya & Jonas: The Read-Receipt Regency",observations:[{subject_id:"maya",text:"Maya arrives with a calendar invite for the feeling and a backup poll for the calendar invite."},{subject_id:"jonas",text:"Jonas replies to the practical question first, then returns five minutes later with the emotional patch notes."}],receipt:{quote:"Sorry—I should have answered the actual question.",note:"A successful repair, delivered like a software update."},closing:"May their plans be explicit and their subtext finally receive paid leave.",seriously:["The warmth is real.","Pair schedule updates with direct reassurance: ‘I still want to see you; I can confirm by six.’"],subjects:[{id:"maya",display_name:"Maya"},{id:"jonas",display_name:"Jonas"}],source_type:"analysis",tone:"playful",safety_mode:false};
export const wrappedExample: WrappedStats={period:{kind:"year",from:"2025-01-01",to:"2025-12-31",label:"2025"},sessionGapHours:6,totals:{messages:4286,withTime:4286,withoutTime:0,participants:2,attachments:318,system:0,deleted:14,words:23740,activeDays:286,firstTs:"2025-01-02T10:10:00Z",lastTs:"2025-12-30T21:05:00Z"},participants:[{id:"a",name:"Person A",messages:2248,share:.524,words:12610,avgWords:5.6,emojis:481},{id:"b",name:"Person B",messages:2038,share:.476,words:11130,avgWords:5.5,emojis:399}],initiation:{sessions:412,byParticipant:[{id:"b",name:"Person B",starts:218,share:.529},{id:"a",name:"Person A",starts:194,share:.471}]},replies:[{id:"a",name:"Person A",replies:892,medianReplyMinutes:12},{id:"b",name:"Person B",replies:844,medianReplyMinutes:18}],busiest:{day:{key:"2025-08-16",count:94},month:{key:"2025-08",count:502},weekday:{key:"Sunday",count:731},hour:{key:"20",count:486}},emojis:[{emoji:"😂",count:214},{emoji:"❤️",count:176},{emoji:"🥲",count:88}],limitations:["Stats describe this imported chat and selected period only."]};
