import type { AnalysisResult, ContextData } from "@/lib/analysis-types";
import type { GroupResultJson, GroupStatsJson } from "@/lib/group/types";
import type { GroupRoastResult } from "@/lib/groupRoast/types";
import type { RoastResultJson } from "@/lib/roast/types";
export { calculatedWrappedExample as wrappedExample } from "./sourceFixtures";

export const deepContext: ContextData = { name1: "Maya", name2: "Jonas", relationship_stage: "dating", duration: "8 months", goal: "Understand our planning loop" };
export const deepResult: AnalysisResult = {
 coverage:{messages_supplied:12,messages_analyzed:12,messages_read_by_ai:12,messages_quoted_verbatim:3,chunk_count:1,failed_chunks:0,full_history_read:true},
 meta:{messages_analyzed:12,analysis_confidence:"medium",safety_concern:false},
 headline:{score:76,tier_label:"Strong connection, uneven clarity",vibe_summary:"Warmth is easy here; logistics become harder when reassurance stays implied."},
 sub_scores:{communication:72,emotional_safety:82,spark:79},
 communication_diagnostic:{response_time_asymmetry:"Jonas is slower during work hours",initiator_balance:"Maya sent 7 messages · Jonas sent 5",message_length_asymmetry:"Message lengths are similar in this excerpt",question_ratio:"Maya asks all four direct questions in this excerpt",key_observation:"Both repair quickly, but plans drift when neither states the reassurance they need."},
 attachment_profiles:{Maya:{primary_style:"anxious",scores:{secure:61,anxious:72,avoidant:18,disorganized:8},confidence:"medium",evidence_quotes:["Are we still on for Friday? No stress if work is wild."]},Jonas:{primary_style:"secure",scores:{secure:74,anxious:20,avoidant:35,disorganized:6},confidence:"medium",evidence_quotes:["Yes. Sorry—I should have answered the actual question."]}},
 four_horsemen:{criticism:{present:false},contempt:{present:false},defensiveness:{present:true,evidence_quote:"I said work was bad, I wasn't ignoring you."},stonewalling:{present:false}},
 bids_for_connection:{turned_toward_pct:78,turned_away_pct:18,turned_against_pct:4},
 love_languages:{Maya:["quality time","words of affirmation"],Jonas:["acts of service","quality time"]},
 green_flags:[{title:"Repair attempts land",evidence:"Both acknowledge misunderstandings and return to the question."},{title:"Mutual curiosity",evidence:"Both ask follow-up questions about each other's day."}],
 yellow_flags:[{title:"Reassurance gets hidden inside logistics",evidence:"Planning questions carry emotional weight that neither names directly."}],red_flags:[],
 hidden_pattern:{title:"The logistics–reassurance loop",description:"Maya asks about the plan to check connection; Jonas answers the practical detail and misses the emotional question. A direct reassurance plus a concrete update breaks the loop."},
 conversation_prompts:["When plans are uncertain, what kind of update helps each of us feel considered?","Can we distinguish 'I need reassurance' from 'I need a schedule'?","What repair phrase feels natural when one of us misses the real question?"],
 compatibility_implication:"Their strongest shared pattern is quick repair. The growth edge is making reassurance explicit before solving logistics."
};
export const quickExample = { verdict:"Interested, but trying not to overpromise", read:"The message is warm and specific, but the softener suggests they are protecting against disappointing you if work runs late.", signals:["They propose a real day rather than saying 'sometime'.","The apology comes before the boundary, which softens it.","They leave the time open, so a concrete follow-up is still needed."], flag:"No clear red flag in this message alone. Context could change the read.", replies:[{tone:"Warm",text:"Thursday works. Want to pick a time once you know how work looks?"},{tone:"Direct",text:"I'm free Thursday after 7—does that work for you?"},{tone:"Low-key",text:"Thursday could work. Let me know when you know your timing."}] };
export const groupResult: GroupResultJson = {group_title:"The Calendar Coalition",group_summary:"Four friends keep plans alive through practical follow-through, quick humor, and one recurring gap: decisions stay open until Maya turns options into a question.",participants:[{id:"p1",display_name:"Maya"},{id:"p2",display_name:"Dev"},{id:"p3",display_name:"Priya"},{id:"p4",display_name:"Sam"}],role_cards:[{participant_id:"p1",role:"The Closer",headline:"Turns a cloud of ideas into an actual plan.",why:"Maya asks decision questions and summarizes agreed details.",evidence:"So Saturday at 7, mine?"},{participant_id:"p2",role:"The Fixer",headline:"Answers practical requests before the thread can wander.",why:"Dev volunteers for errands and confirms tasks clearly.",evidence:"I'll sort snacks."},{participant_id:"p3",role:"The Spark",headline:"Starts ideas and keeps everyone responding.",why:"Priya opens the plan and follows up warmly.",evidence:"Should we do food or just snacks?"},{participant_id:"p4",role:"The Cameo",headline:"Fewer messages, clearly timed.",why:"Sam contributes only twice, so this role is lower-confidence; the available messages concern availability.",evidence:"Can't, work thing — sorry, I read the date wrong."}],balance:{note:"Maya and Priya each send 5 of 16 messages; Dev sends 4. Sam has only 2 messages, so conclusions about Sam are limited.",flag:"moderately uneven"},initiation:{available:true,note:"Priya starts the first dated session; Sam starts the second after an overnight gap."},unanswered:{note:"All five direct questions receive an answer in this excerpt."},repair:{note:"Sam's date mix-up is met with acknowledgment and a concrete alternative rather than blame."},group_strengths:["People volunteer help without scorekeeping.","Humor supports decisions rather than derailing them.","The group welcomes a clear summary."],subgroups:[{note:"Maya and Priya build the plan together; Dev then operationalizes it.",confidence:"medium"}],suggestions:["End planning threads with one owner, time and location.","Ask quieter members a direct low-pressure preference question."],alternatives:["The uneven message share may reflect availability during this excerpt, not influence outside the chat."],confidence:"medium",coverage:{messages_supplied:16,messages_analyzed:16,messages_read_by_ai:16,messages_quoted_verbatim:4,chunk_count:1,failed_chunks:0,full_history_read:true,sampled:false,date_start:"2026-05-08",date_end:"2026-05-09",timestamp_coverage_pct:100}};
export const groupStats: GroupStatsJson = {message_count:16,participant_count:4,has_timestamps:true,timestamp_coverage_pct:100,total_questions:6,total_unanswered_questions:0,participants:[{id:"p1",messages:5,share_pct:31.25,avg_words:6,questions_asked:4,questions_unanswered:0,emoji_count:0,apology_tokens:0,initiations:0,median_response_minutes:6,quiet:false},{id:"p2",messages:4,share_pct:25,avg_words:5,questions_asked:0,questions_unanswered:0,emoji_count:0,apology_tokens:0,initiations:0,median_response_minutes:3,quiet:false},{id:"p3",messages:5,share_pct:31.25,avg_words:6,questions_asked:2,questions_unanswered:0,emoji_count:2,apology_tokens:0,initiations:1,median_response_minutes:3,quiet:false},{id:"p4",messages:2,share_pct:12.5,avg_words:7,questions_asked:0,questions_unanswered:0,emoji_count:1,apology_tokens:1,initiations:1,median_response_minutes:13,quiet:true}]};
export const groupRoastResult: GroupRoastResult={group_headline:"Four planners enter. One plan eventually leaves.",group_personality:"A high-functioning committee disguised as a snack discussion: warm, responsive, and constitutionally unable to choose a date on the first attempt.",participants:groupResult.participants,participant_roles:[{participant_id:"p1",role:"Chief Calendar Officer",headline:"Has never met an open loop she couldn't turn into a poll.",observed_behavior:"Maya asks decision questions and restates settled details.",evidence:"So Saturday at 7, mine?",confidence:"high"},{participant_id:"p2",role:"Minister of Snacks",headline:"Quiet until logistics need rescuing, then suddenly has a spreadsheet.",observed_behavior:"Dev volunteers for practical tasks and confirms completion.",evidence:"I'll sort snacks.",confidence:"high"},{participant_id:"p3",role:"Director of New Business",headline:"Launches the plan and keeps the replies moving.",observed_behavior:"Priya opens the social planning thread and asks the food question.",evidence:"Should we do food or just snacks?",confidence:"high"},{participant_id:"p4",role:"Special Guest Star",headline:"Limited screen time; important plot twist.",observed_behavior:"Sam has only two messages in this excerpt, both about availability, so broader claims would be guesswork.",evidence:"Can't, work thing — sorry, I read the date wrong.",confidence:"low"}],interaction_dynamics:["Priya generates options; Maya turns them into decisions.","Dev's practical replies keep plans moving.","Sam's lower volume means the chat shows availability, not a full personality picture."],standout_moments:[{moment:"A snack question became a hosting plan within six replies.",evidence:"I'll sort snacks."},{moment:"The confirmation changed after Sam corrected the date.",evidence:"No problem. Sunday at 7 instead?"}],seriously:"This group already repairs confusion kindly. One named decision-owner per plan would reduce follow-ups without changing the warmth.",coverage:{messages_supplied:16,messages_read_by_ai:16,chunk_count:1,failed_chunks:0,full_history_read:true,date_start:"2026-05-08",date_end:"2026-05-09"}};
export const roastExample: RoastResultJson={headline:"Maya & Jonas: The Read-Receipt Regency",observations:[{subject_id:"maya",text:"Maya arrives with a calendar invite for the feeling and a backup poll for the calendar invite."},{subject_id:"jonas",text:"Jonas replies to the practical question first, then returns five minutes later with the emotional patch notes."}],receipt:{quote:"Sorry—I should have answered the actual question.",note:"A successful repair, delivered like a software update."},closing:"May their plans be explicit and their subtext finally receive paid leave.",seriously:["The warmth is real.","Pair schedule updates with direct reassurance: ‘I still want to see you; I can confirm by six.’"],subjects:[{id:"maya",display_name:"Maya"},{id:"jonas",display_name:"Jonas"}],source_type:"analysis",tone:"playful",safety_mode:false};
