import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import type { ReactNode } from "react";
import { useState } from "react";

/** Presentation shared by fictional examples and source-backed account summaries. */
export function DashboardScope({ value, options, onChange }: { value: string; options: { value: string; label: string }[]; onChange: (value: string) => void }) {
  return <label className="flex items-center gap-3 text-sm text-muted-foreground">Relationship scope <select aria-label="Relationship scope" value={value} onChange={(event) => onChange(event.target.value)} className="min-h-11 min-w-0 max-w-full rounded-md border border-input bg-background px-3 text-base text-foreground">{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>;
}
export function DashboardPanel({ heading, children, className = "" }: { heading: string; children: ReactNode; className?: string }) {
  return <section className={`min-w-0 rounded-lg border border-border bg-card p-4 sm:p-5 ${className}`}><h2 className="font-display text-lg font-bold">{heading}</h2><div className="mt-3 min-w-0 text-sm leading-relaxed">{children}</div></section>;
}
export function DashboardPattern({ title, statement, sources, children, onSourceSelect }: { title: string; statement: string; sources: { id: string; label: string; date?: string; href?: string }[]; children?: ReactNode; onSourceSelect?: (id: string) => void }) {
  return <DashboardPanel heading="What keeps showing up"><h3 className="font-semibold text-prism-lavender">{title}</h3><p className="mt-2 text-muted-foreground">{statement}</p><p className="mt-4 text-xs text-muted-foreground">{sources.length ? `Supported by ${sources.length} included read${sources.length === 1 ? "" : "s"} with explicit references` : "Source incidence is not established for this pattern."}</p>{sources.length > 0 && <ul className="mt-2 grid gap-2 sm:grid-cols-3">{sources.slice(0, 3).map((source) => <li key={source.id} className="min-w-0 rounded-md border border-border bg-muted/30 p-2 text-xs">{onSourceSelect ? <Button type="button" variant="ghost" className="h-auto min-h-11 w-full justify-start whitespace-normal px-0 text-left underline" onClick={() => onSourceSelect(source.id)}>{source.label}</Button> : source.href ? <a href={source.href} onClick={(event) => { if (source.href === "#manage-conversations") { event.preventDefault(); const manager = document.getElementById("manage-conversations") as HTMLDetailsElement | null; if (manager) { manager.open = true; const summary = manager.querySelector("summary"); summary?.scrollIntoView({ block: "start", behavior: "smooth" }); summary?.focus(); } } }} className="block min-h-11 content-center break-words underline underline-offset-4">{source.label}</a> : <span className="block break-words">{source.label}</span>}{source.date && <span className="block text-muted-foreground">{source.date}</span>}</li>)}</ul>}{children}</DashboardPanel>;
}
export function AddReadLinks({ className = "" }: { className?: string }) {
  const [open, setOpen] = useState(false);
  return <div className={className}><Button type="button" className="min-h-12 w-full" aria-expanded={open} onClick={() => setOpen((current) => !current)}>Add a conversation</Button>{open && <div className="mt-3"><p className="text-sm text-muted-foreground">Choose a read to start. A completed saved read needs your identity confirmed before it can join your profile.</p><div className="mt-3 grid gap-2 sm:grid-cols-3"><Button asChild variant="outline" className="min-h-11"><Link to="/quick?from=relationship360">Quick Take</Link></Button><Button asChild variant="outline" className="min-h-11"><Link to="/deep?from=relationship360">Deep Read</Link></Button><Button asChild variant="outline" className="min-h-11"><Link to="/group-roast?from=relationship360">Group Roast</Link></Button></div></div>}</div>;
}
