import { useEffect, useState } from "react";
import { Helmet } from "react-helmet-async";
import { Link, useParams } from "react-router-dom";
import { ArrowRight, Loader2 } from "lucide-react";
import { Header } from "@/components/chemistry/Header";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import type { GroupRoastShareSnapshot } from "@/lib/groupRoast/types";
export default function GroupRoastShareView(){
 const {token}=useParams<{token:string}>(); const [snapshot,setSnapshot]=useState<GroupRoastShareSnapshot|null>(null); const [gone,setGone]=useState(false);
 useEffect(()=>{let active=true;(async()=>{if(!token){setGone(true);return;}const {data,error}=await supabase.functions.invoke("group-roast-data",{body:{action:"resolve",token}});if(!active)return;if(error||!data?.snapshot)setGone(true);else setSnapshot(data.snapshot as GroupRoastShareSnapshot);})();return()=>{active=false};},[token]);
 return <div className="min-h-screen bg-btln-paper text-foreground"><Helmet><title>A shared Group Roast | BetweenTheLines</title><meta name="description" content="A privacy-safe Group Roast snapshot."/><meta name="robots" content="noindex,nofollow"/></Helmet><Header/><main className="mx-auto max-w-2xl px-5 pb-20 pt-10 sm:px-8">{gone?<><h1 className="text-2xl font-semibold">This link isn't active</h1><p className="mt-3 text-muted-foreground">The owner turned it off, or the link is wrong.</p></>:!snapshot?<p className="flex gap-2 text-muted-foreground"><Loader2 className="animate-spin"/> Opening…</p>:<><p className="text-sm text-muted-foreground">Shared Group Roast · {snapshot.participant_count} people</p><h1 className="mt-3 text-[32px] font-semibold leading-tight">{snapshot.title}</h1><p className="mt-4 text-[17px] text-muted-foreground">{snapshot.personality}</p><ul className="mt-8 space-y-3">{snapshot.roles.map((r,i)=><li key={i} className="rounded-lg border border-border bg-card p-5"><p className="text-sm text-muted-foreground">{r.label}</p><h2 className="mt-1 text-xl font-semibold">{r.role}</h2><p className="mt-2">{r.headline}</p><p className="mt-2 text-sm text-muted-foreground">{r.observed_behavior}</p>{r.evidence&&<blockquote className="mt-3 border-l-2 border-btln-wordmark-accent pl-3 text-sm italic text-muted-foreground">“{r.evidence}”</blockquote>}</li>)}</ul>{snapshot.dynamics.length>0&&<section className="mt-8"><h2 className="text-xl font-semibold">The group dynamic</h2><ul className="mt-3 space-y-2">{snapshot.dynamics.map((d,i)=><li key={i} className="rounded-lg border border-border bg-card p-4">{d}</li>)}</ul></section>}<section className="mt-8 rounded-lg bg-btln-mint/40 p-5"><h2 className="text-xl font-semibold">But seriously…</h2><p className="mt-2">{snapshot.seriously}</p></section><p className="mt-6 text-sm text-muted-foreground">This is a deliberate snapshot. It does not include the private transcript or give access to the source chat.</p></>}<Button asChild className="mt-8 rounded-full"><Link to="/group-roast">Roast your own group <ArrowRight/></Link></Button></main></div>;
}
