import { Link } from "react-router-dom";
import logoAsset from "@/assets/logo.png.asset.json";

export default function Terms() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="border-b border-border px-5 py-4 sm:px-8">
        <div className="mx-auto flex max-w-3xl items-center justify-between">
          <Link to="/" className="flex items-center">
            <img src={logoAsset.url} alt="BetweenTheLines" className="h-12 w-auto" />
          </Link>
          <Link to="/" className="text-[14px] text-muted-foreground hover:text-foreground">
            ← Back
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-5 py-10 sm:px-8 sm:py-16">
        <h1 className="text-[32px] font-medium tracking-tight sm:text-[40px]">
          Terms of Service
        </h1>
        <p className="mt-3 text-[15px] text-muted-foreground">
          These Terms of Service govern your use of BetweenTheLines. By using the app, you agree to these terms.
          This page is maintained by BetweenTheLines and may be updated from time to time.
        </p>

        <section className="mt-10 space-y-3">
          <h2 className="text-[20px] font-medium">Important Legal Disclaimer</h2>
          <div className="rounded-xl border border-border bg-muted/30 p-5">
            <p className="text-[15px] leading-relaxed text-muted-foreground">
              <strong>BetweenTheLines is a relationship coaching tool, not a healthcare service.</strong> The app
              does not provide psychotherapy, psychiatric advice, counseling, diagnosis, treatment, or any
              form of mental health care. The analysis and reports generated by this app are for informational
              and coaching purposes only. They are not a substitute for professional advice from a licensed
              therapist, counselor, psychiatrist, psychologist, or other qualified mental health professional.
            </p>
            <p className="mt-3 text-[15px] leading-relaxed text-muted-foreground">
              <strong>If you are experiencing a mental health crisis, thoughts of self-harm, or abuse,</strong>{" "}
              please contact emergency services or a licensed mental health professional immediately. Do not
              rely on this app for crisis intervention or clinical support.
            </p>
          </div>
        </section>

        <section className="mt-10 space-y-3">
          <h2 className="text-[20px] font-medium">1. Description of Service</h2>
          <p className="text-[15px] leading-relaxed text-muted-foreground">
            BetweenTheLines provides an AI-powered relationship coaching tool that analyzes text conversations
            or screenshots and generates reports about relationship dynamics, patterns, and communication styles.
            The service is intended for self-reflection and coaching purposes only.
          </p>
        </section>

        <section className="mt-10 space-y-3">
          <h2 className="text-[20px] font-medium">2. Eligibility</h2>
          <p className="text-[15px] leading-relaxed text-muted-foreground">
            You must be at least 18 years old to use BetweenTheLines. By using the service, you represent
            that you meet this requirement. If you are using the service on behalf of someone else, you
            represent that you have the authority to bind them to these terms.
          </p>
        </section>

        <section className="mt-10 space-y-3">
          <h2 className="text-[20px] font-medium">3. User Accounts</h2>
          <ul className="list-disc space-y-2 pl-5 text-[15px] leading-relaxed text-muted-foreground">
            <li>You may use the service anonymously or create an account to save reports.</li>
            <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
            <li>You agree to provide accurate information when creating an account.</li>
            <li>You may delete your account and associated data at any time by contacting us.</li>
          </ul>
        </section>

        <section className="mt-10 space-y-3">
          <h2 className="text-[20px] font-medium">4. Acceptable Use</h2>
          <p className="text-[15px] leading-relaxed text-muted-foreground">
            You agree not to use BetweenTheLines to:
          </p>
          <ul className="list-disc space-y-2 pl-5 text-[15px] leading-relaxed text-muted-foreground">
            <li>Violate any applicable law or regulation.</li>
            <li>Infringe on the rights of others, including privacy and intellectual property rights.</li>
            <li>Upload or analyze content that is illegal, harmful, threatening, abusive, or defamatory.</li>
            <li>Attempt to reverse engineer, decompile, or exploit the service.</li>
            <li>Interfere with the proper functioning of the service or its infrastructure.</li>
            <li>Use automated systems or bots to access the service without authorization.</li>
          </ul>
        </section>

        <section className="mt-10 space-y-3">
          <h2 className="text-[20px] font-medium">5. Content and Intellectual Property</h2>
          <p className="text-[15px] leading-relaxed text-muted-foreground">
            You retain ownership of the conversation content you submit. By submitting content, you grant
            us a limited license to process it solely for the purpose of generating your report. We do not
            claim ownership of your content and do not use it to train AI models.
          </p>
          <p className="text-[15px] leading-relaxed text-muted-foreground">
            The BetweenTheLines name, logo, and all related intellectual property belong to us. You may not
            use them without our prior written consent.
          </p>
        </section>

        <section className="mt-10 space-y-3">
          <h2 className="text-[20px] font-medium">6. Payments and Refunds</h2>
          <p className="text-[15px] leading-relaxed text-muted-foreground">
            Some features of BetweenTheLines require payment. Payments are processed securely through Stripe.
            Pricing is displayed before purchase. Refunds are handled on a case-by-case basis. If you
            believe you are entitled to a refund, please contact us.
          </p>
        </section>

        <section className="mt-10 space-y-3">
          <h2 className="text-[20px] font-medium">7. Disclaimer of Warranties</h2>
          <p className="text-[15px] leading-relaxed text-muted-foreground">
            BetweenTheLines is provided "as is" and "as available" without warranties of any kind, either
            express or implied. We do not warrant that the service will be uninterrupted, error-free, or
            that any results obtained from using the service will be accurate or reliable.
          </p>
          <p className="text-[15px] leading-relaxed text-muted-foreground">
            The relationship analysis and reports generated by the app are based on AI interpretation of
            text and should not be treated as definitive truth. Human judgment and context are essential.
            We make no claims about the accuracy, completeness, or usefulness of any report for any
            specific purpose.
          </p>
        </section>

        <section className="mt-10 space-y-3">
          <h2 className="text-[20px] font-medium">8. Limitation of Liability</h2>
          <p className="text-[15px] leading-relaxed text-muted-foreground">
            To the maximum extent permitted by law, BetweenTheLines and its operators shall not be liable
            for any indirect, incidental, special, consequential, or punitive damages arising out of or
            relating to your use of the service. This includes, without limitation, damages for loss of
            profits, goodwill, data, or other intangible losses.
          </p>
          <p className="text-[15px] leading-relaxed text-muted-foreground">
            In no event shall our total liability exceed the amount you paid to use the service in the
            twelve (12) months preceding the claim, or $100, whichever is greater.
          </p>
        </section>

        <section className="mt-10 space-y-3">
          <h2 className="text-[20px] font-medium">9. Indemnification</h2>
          <p className="text-[15px] leading-relaxed text-muted-foreground">
            You agree to indemnify and hold harmless BetweenTheLines and its operators from any claims,
            damages, liabilities, costs, or expenses arising out of your use of the service or your violation
            of these terms.
          </p>
        </section>

        <section className="mt-10 space-y-3">
          <h2 className="text-[20px] font-medium">10. Termination</h2>
          <p className="text-[15px] leading-relaxed text-muted-foreground">
            We reserve the right to suspend or terminate your access to the service at any time, with or
            without cause, and with or without notice. Upon termination, your right to use the service
            will immediately cease.
          </p>
        </section>

        <section className="mt-10 space-y-3">
          <h2 className="text-[20px] font-medium">11. Governing Law</h2>
          <p className="text-[15px] leading-relaxed text-muted-foreground">
            These Terms shall be governed by and construed in accordance with the laws of the jurisdiction
            in which BetweenTheLines operates, without regard to its conflict of law provisions. Any disputes
            arising under these terms shall be subject to the exclusive jurisdiction of the courts in that
            jurisdiction.
          </p>
        </section>

        <section className="mt-10 space-y-3">
          <h2 className="text-[20px] font-medium">12. Changes to These Terms</h2>
          <p className="text-[15px] leading-relaxed text-muted-foreground">
            We may modify these Terms of Service at any time. We will notify you of material changes by
            posting the updated terms on this page. Your continued use of the service after changes are
            posted constitutes your acceptance of the revised terms.
          </p>
        </section>

        <section className="mt-10 space-y-3">
          <h2 className="text-[20px] font-medium">13. Contact</h2>
          <p className="text-[15px] leading-relaxed text-muted-foreground">
            If you have questions about these Terms of Service, please contact us through the Feedback
            option in the footer.
          </p>
        </section>

        <p className="mt-12 text-[13px] text-muted-foreground">
          Last updated: June 2026. This page describes current terms and may be updated as the product evolves.
        </p>
      </main>
    </div>
  );
}
