import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Header } from "@/components/chemistry/Header";
import { DeepReport } from "@/pages/Report";
import { WrappedCard } from "@/components/wrapped/WrappedCard";
import { SourceConversation } from "@/components/examples/SourceConversation";
import { deepContext, deepResult, groupResult, groupStats, groupRoastResult, quickExample, roastExample, wrappedExample } from "@/lib/examples/fixtures";
import { EXAMPLES, type ExampleKind } from "@/lib/examples/catalog";
import { groupMessages, pairMessages, quickMessages, wrappedMessages } from "@/lib/examples/sourceFixtures";
import { Relationship360Preview } from "@/components/relationship360/Relationship360Preview";

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => <section className="border-t border-btln-line py-7"><h2 className="text-xl font-semibold">{title}</h2><div className="mt-3 space-y-3 text-[15px] leading-7">{children}</div></section>;
const Evidence = ({ children }: { children: React.ReactNode }) => <blockquote className="border-l-2 border-btln-sage pl-4 text-muted-foreground">“{children}”</blockquote>;
export const ExampleContent = ({ kind, compact = false }: { kind: ExampleKind; compact?: boolean }) => {
  const meta = EXAMPLES.find((entry) => entry.kind === kind) ?? EXAMPLES[0];
  return <main className={compact ? "px-5 pb-28 pt-5" : "mx-auto max-w-3xl px-5 pb-28 pt-8 sm:px-8"}>
    <div className="mb-6"><p className="text-sm font-semibold text-btln-forest">Fictional example</p><h1 className="mt-1 text-3xl font-semibold">{meta.name}</h1><p className="mt-3 text-muted-foreground">Synthetic conversation data demonstrates the complete output. No customer information is used.</p>{kind === "journey" && <p className="mt-3 font-semibold">Illustrative preview — feature in development</p>}</div>
    {kind === "journey" ? <Relationship360Preview /> : <SourceConversation messages={kind === "quick" ? quickMessages : kind === "deep" || kind === "roast" ? pairMessages : kind === "wrapped" ? wrappedMessages : groupMessages} />}

    {kind === "deep" && <DeepReport result={deepResult} context={deepContext} locked={false} />}
    {kind === "quick" && <><Section title="The read"><p className="text-2xl font-semibold">{quickExample.verdict}</p><p>{quickExample.read}</p></Section><Section title="Signals">{quickExample.signals.map(x=><p key={x}>• {x}</p>)}</Section><Section title="What to watch"><p>{quickExample.flag}</p></Section><Section title="Three ways to reply">{quickExample.replies.map(x=><div key={x.tone} className="rounded-md border border-btln-line p-4"><strong>{x.tone}</strong><p>{x.text}</p></div>)}</Section></>}
    {kind === "group" && <><Section title={groupResult.group_title ?? "Group pattern"}><p>{groupResult.group_summary}</p><p><strong>{groupStats.message_count} messages · {groupStats.participant_count} people · complete selected period</strong></p></Section><Section title="Everyone's role">{groupResult.role_cards?.map(r=><article key={r.participant_id} className="rounded-md border border-btln-line p-4"><h3 className="font-semibold">{r.role}: {r.headline}</h3><p>{r.why}</p><Evidence>{r.evidence}</Evidence></article>)}</Section><Section title="Balance"><p>{groupResult.balance?.note}</p><p>{groupResult.initiation?.note}</p><p>{groupResult.unanswered?.note}</p></Section><Section title="Repair"><p>{groupResult.repair?.note}</p></Section><Section title="Group strengths">{groupResult.group_strengths?.map(x=><p key={x}>• {x}</p>)}</Section><Section title="Subgroups and alternatives">{groupResult.subgroups?.map(x=><p key={x.note}>{x.note} <span className="text-muted-foreground">({x.confidence} confidence)</span></p>)}{groupResult.alternatives?.map(x=><p key={x}>{x}</p>)}</Section><Section title="Try next">{groupResult.suggestions?.map(x=><p key={x}>• {x}</p>)}</Section></>}
    {kind === "group-roast" && <><Section title={groupRoastResult.group_headline ?? "Group headline"}><p>{groupRoastResult.group_personality}</p><p><strong>{groupRoastResult.coverage?.messages_supplied} messages · 4 people · complete selected period</strong></p></Section><Section title="The cast">{groupRoastResult.participant_roles?.map(r=><article key={r.participant_id} className="rounded-md border border-btln-line p-4"><h3 className="font-semibold">{r.role}</h3><p className="font-medium">{r.headline}</p><p>{r.observed_behavior}</p>{r.evidence&&<Evidence>{r.evidence}</Evidence>}<p className="text-xs text-muted-foreground">{r.confidence} confidence</p></article>)}</Section><Section title="Group dynamics">{groupRoastResult.interaction_dynamics?.map(x=><p key={x}>• {x}</p>)}</Section><Section title="Standout moments">{groupRoastResult.standout_moments?.map(x=><div key={x.moment}><p>{x.moment}</p>{x.evidence&&<Evidence>{x.evidence}</Evidence>}</div>)}</Section><Section title="But seriously…"><p>{groupRoastResult.seriously}</p></Section></>}
    {kind === "roast" && <><Section title={roastExample.headline ?? "Roast Us"}>{roastExample.observations?.map((x,i)=><p key={i}>• {x.text}</p>)}</Section><Section title="Receipt"><Evidence>{roastExample.receipt?.quote}</Evidence><p>{roastExample.receipt?.note}</p></Section><Section title="Closing"><p>{roastExample.closing}</p></Section><Section title="But seriously…">{roastExample.seriously?.map(x=><p key={x}>{x}</p>)}</Section></>}
    {kind === "wrapped" && <><Section title="Your year, counted"><p>{wrappedExample.totals.messages} messages · {wrappedExample.totals.activeDays} active days · {wrappedExample.totals.attachments} attachment</p><p>{wrappedExample.participants.map(person=>`${person.name} sent ${(person.share*100).toFixed(1)}%`).join("; ")}. {wrappedExample.busiest.weekday?.key} was busiest, and {wrappedExample.busiest.hour ? `${Number(wrappedExample.busiest.hour.key)%12||12}${Number(wrappedExample.busiest.hour.key)>=12?"pm":"am"}` : "no hour"} the busiest hour.</p></Section><div className="mx-auto h-[340px] max-w-[340px] overflow-hidden"><div className="origin-top-left scale-[0.3]"><WrappedCard stats={wrappedExample} names={{a:"Person A",b:"Person B"}} variant="square" /></div></div><Section title="How to read this"><p>These are deterministic counts from the selected period, not a personality score. Missing timestamps and deleted messages would be stated here.</p></Section></>}
    {kind !== "journey" && <div className="mt-8 border-t border-btln-line pt-6"><p className="mb-4 text-sm font-semibold text-btln-forest">Fictional example</p><Button asChild className="min-h-12 rounded-full"><Link to={meta.tryRoute}>Try {meta.name}</Link></Button></div>}
  </main>;
};
export const ExamplePage = ({ kind }: { kind: ExampleKind }) => <div className="min-h-screen bg-btln-paper text-foreground"><Header /><ExampleContent kind={kind} /></div>;
export const ExampleIndex = () => <div className="min-h-screen bg-btln-paper text-foreground"><Header /><main className="mx-auto max-w-3xl px-5 pb-28 pt-8 sm:px-8"><p className="text-sm font-semibold text-btln-forest">Fictional examples</p><h1 className="mt-2 text-3xl font-semibold">See a complete result</h1><p className="mt-3 text-muted-foreground">Every section is open. These examples use synthetic data and never call the analysis service.</p><div className="mt-8 divide-y divide-btln-line border-y border-btln-line">{EXAMPLES.map(x=><Link key={x.kind} to={x.route} className="flex min-h-16 items-center justify-between py-3 font-medium underline-offset-4 hover:underline"><span>{x.name}</span><span aria-hidden>→</span></Link>)}</div></main></div>;
export const SeeExample = ({ kind }: { kind: ExampleKind }) => {
  const [open,setOpen]=useState(false); const opener=useRef<HTMLButtonElement>(null); const close=useRef<HTMLButtonElement>(null);
  useEffect(()=>{ if(!open)return; const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setOpen(false)}; window.addEventListener("keydown",onKey); document.body.style.overflow="hidden"; close.current?.focus(); return()=>{window.removeEventListener("keydown",onKey);document.body.style.overflow="";opener.current?.focus()};},[open]);
  return <><button ref={opener} type="button" onClick={()=>setOpen(true)} className="inline-flex min-h-11 items-center underline underline-offset-4">See Example</button>{open&&<div role="dialog" aria-modal="true" aria-label={`${EXAMPLES.find(x=>x.kind===kind)?.name} fictional example`} className="fixed inset-0 z-[80] overflow-y-auto bg-btln-paper"><div className="sticky top-0 z-10 flex h-[58px] items-center justify-between border-b border-btln-line bg-btln-paper/95 px-[19px]"><span className="font-semibold">Fictional example</span><Button ref={close} type="button" size="icon" variant="ghost" aria-label="Close example" onClick={()=>setOpen(false)} className="h-11 w-11 rounded-full"><X className="h-5 w-5" /></Button></div><ExampleContent kind={kind} compact /></div>}</>;
};
