// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-my-analyses.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_analyses_default = defineTool({
  name: "list_my_analyses",
  title: "List my analyses",
  description: "List the signed-in user's saved conversation analyses (most recent first). Returns id, status, created_at, relationship_type, and couple_type_id.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max rows (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("analyses").select("id, status, created_at, relationship_type, couple_type_id, is_paid, message_count").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { analyses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-analysis.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_analysis_default = defineTool2({
  name: "get_my_analysis",
  title: "Get my analysis",
  description: "Fetch the full result JSON for one of the signed-in user's saved analyses by id.",
  inputSchema: {
    id: z2.string().uuid().describe("Analysis UUID owned by the caller.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("analyses").select("id, status, created_at, completed_at, relationship_type, couple_type_id, is_paid, message_count, context_data, result_json, error_message").eq("id", id).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Analysis not found" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { analysis: data }
    };
  }
});

// src/lib/mcp/tools/get-shared-analysis.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_shared_analysis_default = defineTool3({
  name: "get_shared_analysis",
  title: "Get shared analysis",
  description: "Fetch a publicly shared BetweenTheLines analysis by id. Returns the sanitized report (no raw conversation content).",
  inputSchema: {
    id: z3.string().uuid().describe("Analysis UUID from a public share link.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ id }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.rpc("get_shared_analysis", { p_id: id });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const row = Array.isArray(data) ? data[0] : data;
    if (!row) {
      return { content: [{ type: "text", text: "Shared analysis not found" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(row) }],
      structuredContent: { analysis: row }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ukycdbvasmeuralmvvcm";
var mcp_default = defineMcp({
  name: "betweenthelines-mcp",
  title: "BetweenTheLines",
  version: "0.1.0",
  instructions: "Tools for BetweenTheLines, a relationship conversation analyzer. Use `list_my_analyses` and `get_my_analysis` to browse the signed-in user's saved reports, and `get_shared_analysis` to look up a public share link by id.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_my_analyses_default, get_my_analysis_default, get_shared_analysis_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
