ALTER TABLE public.couple_types ADD COLUMN IF NOT EXISTS extras jsonb NOT NULL DEFAULT '{}'::jsonb;

UPDATE public.couple_types SET extras = '{
 "romantic": {"friction":"Things run so smoothly that small resentments never get said out loud — until they arrive all at once.","advice":"Schedule the boring conversation before you need it. Once a week, ask what each of you is quietly carrying, and say the small thing while it is still small.","examples":["You solve a logistics problem in four messages and neither of you is annoyed.","Praise gets traded easily, but nobody mentions the thing that stung last Tuesday.","Plans get made fast; feelings get filed for later."]},
 "friend": {"friction":"The friendship runs on momentum, so nobody checks whether one of you is quietly doing more of the work.","advice":"Say the unglamorous part out loud: who is planning, who is reaching out, and whether that still feels fair.","examples":["Group plans get sorted in one thread with zero drama.","You hype each other publicly and skip the harder check-in.","A missed call goes unmentioned for weeks."]},
 "family": {"friction":"Being the easy family member can turn into being the one who never gets asked how they are.","advice":"Trade roles sometimes. Let the reliable one be the one who needs something, and let the other one show up for it.","examples":["Logistics land instantly; nobody asks how the week actually went.","Good news travels fast, hard news travels slowly.","Everyone assumes you two are fine, so nobody checks."]}
}'::jsonb WHERE id = 1;

UPDATE public.couple_types SET extras = '{
 "romantic": {"friction":"Stability can slide into routine, and the spark gets postponed because nothing is on fire.","advice":"Protect a small amount of unscheduled time together each week, and ask one question you do not already know the answer to.","examples":["Daily check-ins are warm and reliable.","Conflict gets repaired the same day.","Weeks pass pleasantly with nothing new in them."]},
 "friend": {"friction":"You are so low-maintenance that months can slip by without either of you noticing the gap.","advice":"Put a recurring, low-effort ritual in place — a monthly call or a standing walk — so closeness does not depend on a good week.","examples":["You pick up mid-sentence after six weeks of silence.","Nobody keeps score about who texted last.","Big news sometimes reaches you second-hand."]},
 "family": {"friction":"Calm can become unspoken. Real worries get softened into small talk.","advice":"Ask a slightly bigger question than usual — about health, money, or what they are dreading — and let the silence sit.","examples":["Calls are regular, warm, and mostly practical.","Disagreements cool down quickly.","Serious news gets mentioned casually, late."]}
}'::jsonb WHERE id = 2;

UPDATE public.couple_types SET extras = '{
 "romantic": {"friction":"Warmth is shown through actions, so words of reassurance can run short when one of you needs them.","advice":"Name the feeling once in a while, not just the deed. One direct sentence beats ten helpful gestures for the person waiting to hear it.","examples":["Practical care arrives before anyone asks.","Affection shows up as a charged phone, a saved seat, a lift home.","Big emotional statements feel awkward to type."]},
 "friend": {"friction":"Loyalty is total but unspoken, so the other person can wonder where they stand.","advice":"Say the obvious thing occasionally: that you value them and why. It will feel unnecessary to you and land hard for them.","examples":["You turn up for the hard days without being asked.","Threads are short, favours are large.","Compliments arrive as jokes."]},
 "family": {"friction":"Deep roots, few words — which younger or more expressive family members can read as distance.","advice":"Translate once. Explain that short replies are not coldness, and add one warm line to the practical ones.","examples":["Messages are brief and reliable.","Help is offered as a lift, a meal, a repair.","Feelings are discussed sideways, if at all."]}
}'::jsonb WHERE id = 3;

UPDATE public.couple_types SET extras = '{
 "romantic": {"friction":"Every small change in tone gets read as a signal, so ordinary distance can spiral into a crisis.","advice":"Agree on a plain-language reassurance habit: when something reads badly, ask what it meant before deciding what it meant.","examples":["A slow reply turns into a long analysis.","Apologies are frequent and heartfelt.","Conversations go deep quickly, sometimes too quickly."]},
 "friend": {"friction":"You both feel everything at full volume, which makes the friendship intense and occasionally exhausting.","advice":"Give each other permission to be boring. Not every message needs to carry emotional weight.","examples":["Voice notes run long.","You catch the shift in their mood before they mention it.","Small misunderstandings get processed at length."]},
 "family": {"friction":"Big feelings collide, and old history makes every current disagreement heavier than it needs to be.","advice":"Separate today from the archive. Name which one you are actually arguing about before you continue.","examples":["A simple question becomes a long conversation.","Love is expressed openly and often.","Old arguments resurface inside new ones."]}
}'::jsonb WHERE id = 4;

UPDATE public.couple_types SET extras = '{
 "romantic": {"friction":"Space is protected so well that closeness has to be scheduled, and neither of you wants to be the one asking.","advice":"Make reaching out a neutral act, not a demand. Agree on one moment in the day that belongs to both of you.","examples":["Long, comfortable silences between messages.","Plans are made around two full lives.","Neither of you wants to seem needy."]},
 "friend": {"friction":"Side-by-side works until one of you needs something and has no practice asking.","advice":"Ask directly once. The friendship can hold it, and the other person almost certainly wants the chance.","examples":["You share interests more than updates.","Months pass, nothing is broken.","Help is offered but rarely requested."]},
 "family": {"friction":"Breathing room can look like indifference from the outside, and sometimes from the inside too.","advice":"Set a light, predictable rhythm of contact so nobody has to interpret the gaps.","examples":["Everyone respects everyone else privacy.","Check-ins are short and infrequent.","Nobody is quite sure who should call first."]}
}'::jsonb WHERE id = 5;

UPDATE public.couple_types SET extras = '{
 "romantic": {"friction":"One of you pursues when anxious and the other withdraws to think — and each move triggers the other.","advice":"Name the pattern while calm, and agree a pause with a return time: step away for an hour, but say when you will be back.","examples":["Double texts followed by a long silence.","One wants to sort it now, the other wants space first.","Repairs come after the storm, and they work."]},
 "friend": {"friction":"One friend maintains the thread while the other appears in bursts, and the maintainer quietly keeps score.","advice":"Say what you need in concrete terms — a reply within a day, not constant contact — and let the other agree to something real.","examples":["Weeks of silence, then a four-hour catch-up.","One initiates almost every plan.","Neither doubts the friendship, both feel the rhythm."]},
 "family": {"friction":"Different contact needs get read as different levels of love.","advice":"Agree a floor, not a ceiling: a minimum both of you can keep, without guilt on top.","examples":["One calls weekly, one replies monthly.","Guilt appears in the phrasing of check-ins.","Reunions are warm regardless of the gaps."]}
}'::jsonb WHERE id = 6;

UPDATE public.couple_types SET extras = '{
 "romantic": {"friction":"One of you is always the steady one, which quietly stops them from ever being the one who needs help.","advice":"Deliberately swap. Let the steady partner say what they are struggling with, and let the other hold it without fixing it.","examples":["One reassures, the other settles.","Worry gets voiced and then answered.","The calmer one rarely says they are tired."]},
 "friend": {"friction":"The support flows one way long enough that it starts to feel like a role rather than a friendship.","advice":"Check the balance out loud every so often, and ask the listener what is going on with them first.","examples":["One friend brings the problems, the other brings perspective.","Advice is given gently and taken well.","The steady one deflects when asked about themselves."]},
 "family": {"friction":"The dependable family member becomes everyone default, and resentment builds where gratitude should be.","advice":"Share the load explicitly, and thank the steady one in words, not just assumptions.","examples":["One person handles the crises.","Everyone calls the same person first.","Nobody asks that person how they are coping."]}
}'::jsonb WHERE id = 7;

UPDATE public.couple_types SET extras = '{
 "romantic": {"friction":"Closeness is being constructed carefully, so spontaneity and full trust are still catching up.","advice":"Keep doing the small, reliable things and let them count. Say what you are working towards so the effort is visible to both of you.","examples":["Plans and promises get followed through.","Openness arrives in measured steps.","You both notice when a boundary is respected."]},
 "friend": {"friction":"A friendship built on purpose can feel effortful, and either of you may wonder if it is mutual.","advice":"Say it plainly: you like this person and you want the friendship. Certainty removes most of the effort.","examples":["Catch-ups are planned, not accidental.","You check that the other is comfortable.","Warmth grows steadily rather than instantly."]},
 "family": {"friction":"You are rebuilding something that was strained, and progress can feel slow and easily set back.","advice":"Keep the bar small and repeatable. Consistency over months does more than one big conversation.","examples":["Contact is deliberate and increasing.","Old topics get approached carefully.","Both sides notice and appreciate the effort."]}
}'::jsonb WHERE id = 8;

UPDATE public.couple_types SET extras = '{
 "romantic": {"friction":"You want the same things but express them in different keys, so good intentions get heard as criticism.","advice":"Before responding, say back what you think they meant. Most of your arguments are translation problems, not disagreements.","examples":["One writes paragraphs, one writes a line.","You end up agreeing after the argument.","Tone gets misread more than content does."]},
 "friend": {"friction":"Different communication speeds make one of you feel rushed and the other feel left hanging.","advice":"Agree how urgent is urgent, and use a call for anything that needs tone attached.","examples":["One replies instantly, one replies tonight.","Jokes occasionally land wrong and get fixed.","You are rarely actually in conflict."]},
 "family": {"friction":"Different generations, different styles — the meaning gets lost in the format.","advice":"Match their channel sometimes. A call, a voice note, or a visit carries what text cannot.","examples":["A short reply gets taken as annoyance.","Advice is offered and heard as judgement.","You clear it up once you actually talk."]}
}'::jsonb WHERE id = 9;

UPDATE public.couple_types SET extras = '{
 "romantic": {"friction":"There is real care here, but conflict escalates faster than either of you can slow it down.","advice":"Use a time-out you both agree on in advance, and come back to the same conversation within a day. Consider a couples counsellor if the same fight keeps returning.","examples":["Arguments get sharp, then apologetic.","Both of you keep showing up anyway.","Repairs happen, but the same theme returns."]},
 "friend": {"friction":"Honesty is a strength, but bluntness lands harder than either of you intends.","advice":"Lead with the intent before the critique, and check in after a hard conversation rather than assuming it was fine.","examples":["You tell each other uncomfortable truths.","Silences follow the harder conversations.","The friendship survives things others would not."]},
 "family": {"friction":"Long history means conflicts have grooves, and you both fall into them quickly.","advice":"Change one step in the pattern — the timing, the setting, the first sentence — and see whether the rest follows.","examples":["The same argument, in slightly different words.","Warmth returns quickly after the blow-up.","Neither of you walks away for good."]}
}'::jsonb WHERE id = 10;

UPDATE public.couple_types SET extras = '{
 "romantic": {"friction":"You are living parallel lives and handling the hard parts alone, which slowly turns partners into housemates.","advice":"Start small and specific: one shared decision, one honest conversation a week. If contempt has crept in, a professional third party helps more than effort alone.","examples":["Problems get solved separately.","Messages are logistical more than personal.","Neither of you asks for much anymore."]},
 "friend": {"friction":"The friendship has drifted into updates rather than closeness, and nobody has named it.","advice":"Say you miss them. It is the whole fix, and it works more often than it feels like it will.","examples":["Conversations stay on the surface.","Plans are discussed, rarely booked.","You both still care, quietly."]},
 "family": {"friction":"Distance has become the norm, and reaching across it feels like admitting something.","advice":"Send the low-stakes message — a photo, a memory, a question — and let contact rebuild before the big conversation.","examples":["Contact is occasional and polite.","Real news arrives through other people.","Both sides are waiting for the other."]}
}'::jsonb WHERE id = 11;

UPDATE public.couple_types SET extras = '{
 "romantic": {"friction":"There is not much said, so small distances go unexamined and slowly add up.","advice":"Add one real question to the daily logistics. Closeness grows from ordinary detail, not big declarations.","examples":["Short, functional messages.","Presence matters more than words.","Neither of you raises small issues."]},
 "friend": {"friction":"Comfortable quiet can be hard to tell apart from drifting.","advice":"Make contact concrete: suggest a date and a place rather than we should catch up.","examples":["Long gaps, no hard feelings.","Conversations restart easily.","Plans stay vague."]},
 "family": {"friction":"Everyone assumes the bond is understood, so nothing gets said that would confirm it.","advice":"Say the plain thing once — that you are glad they are there. It carries further than you expect.","examples":["Brief, steady contact.","Nobody asks for much.","The bond is assumed rather than expressed."]}
}'::jsonb WHERE id = 12;

UPDATE public.couple_types SET extras = '{
 "romantic": {"friction":"The same intensity that creates the spark makes conflict burn hot and fast.","advice":"Keep the heat, lose the sharp edges: no contempt, no name-calling, and a hard stop when either of you is flooded.","examples":["Big highs, quick flare-ups.","Making up is as intense as falling out.","Neither of you does lukewarm."]},
 "friend": {"friction":"Banter is the love language, which means a genuine hurt can hide inside a joke.","advice":"Have one signal that means I am being serious now, and honour it without teasing.","examples":["Constant mutual roasting.","Real affection under the insults.","An occasional joke that stings longer."]},
 "family": {"friction":"Loud, loyal, and quick to argue — the volume can make others feel like it is worse than it is.","advice":"Keep the arguing about the topic, and close the loop the same day so nothing calcifies.","examples":["Voices rise, then everyone eats together.","Opinions are strong and stated.","Loyalty is never actually in doubt."]}
}'::jsonb WHERE id = 13;